export class CertEnlist   {
    constructor(
        public  id?: string,
        public  eduCertChannelId?: string,
        public  examBatch?: string,
        public  authType?: string,
        public  eduUserId?: string,
        public  name?: string,
        public  gender?: string,
        public  birthday?: Date,
        public  nameSpell?: string,
        public  idCard?: string,
        public  mobile?: string,
        public  profession?: string,
        public  email?: string,
        public  education?: string,
        public  examineSubject?: string,
        public  authProdect?: string,
        public  authGrade?: string,
        public  address?: string,
        public  examineTime?: Date,
        public  examineType?: string,
        public  chargeType?: string,
        public  chargeAmount?: number,
        public  isCharge?: string,
        public  isOk?: string,
        public  isPass?: string,
        public  orderNum?: number,
        public  remark?: string,
    ) {}
}
